services:
  gitlab-web:
    image: gitlab/gitlab-ce:latest
    restart: on-failure
    hostname: 'localhost'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - ${GITLAB_HTTP_PORT}:80
      - ${GITLAB_HTTPS_PORT}:443
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    networks:
      - gitlab
    shm_size: 256m
    cpus: ${BIG_CPUS}
    mem_reservation: ${BIG_MEM_RESERVATION}
    mem_limit: ${BIG_MEM_LIMIT}
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner    
    restart: on-failure
    depends_on:
      - gitlab-web
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab
    cpus: ${SMALL_CPUS}
    mem_reservation: ${SMALL_MEM_RESERVATION}
    mem_limit: ${SMALL_MEM_LIMIT}
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: on-failure
    ports:
      - ${JENKINS_HTTP_PORT}:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins
    cpus: ${BIG_CPUS}
    mem_reservation: ${BIG_MEM_RESERVATION}
    mem_limit: ${BIG_MEM_LIMIT}
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: on-failure
    ports:
      - ${NEXUS_HTTP_PORT}:8081
    volumes:
      - /srv/nexus/nexus-data:/nexus-data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nexus
    cpus: ${BIG_CPUS}
    mem_reservation: ${BIG_MEM_RESERVATION}
    mem_limit: ${BIG_MEM_LIMIT}
volumes:
  jenkins_home:
networks:
  gitlab:
    name: gitlab-network
  jenkins:
    name: jenkins-network
  nexus:
    name: nexus-network